# Задание 8 (финальное)

В этом задании Вам предлагается сделать несколько несложных упражнений с упомянутыми на лекции библиотеками, а также потренироваться использовать документацию к новым для Вас библиотекам, чтобы почувствовать, что теперь Вы сами можете продолжить свое знакомство с Питоном, осваивая новые инструменты.

## 1. Базовый уровень: задание по numpy и scipy

1. Напишите свой аналог np.linspace с использованием цикла и с использованием list comprehension. Сравните все три варианта по производительности
1. Сравните по производительности основные операции с массивами (array) numpy и с list
1. Попробуйте поменять метод оптимизации в примере решения оптимизационной задачи с помощью scipy.optimize, показанном на лекции (для этого потребуется обратиться к документации). Подберите метод с наименьшим количеством вычислений функции. Начальное приближение (точку [5,5]) оставьте тем же.

In [1]:
import numpy as np

<b>Решение задачи 1:</b> Согласно документации полный формат вызова функции - <b>numpy.linspace(start, stop, num = 50, endpoint = True, retstep = False)</b>.

In [2]:
# с использованием цикла
def my_linspace_circle(start, stop, num=50, endpoint=True, retstep=False):
    list_range = []
    if endpoint:
        step = float(stop - start) / (num-1)
    else:
        step = float(stop - start) / num
    for i in range(num):
        list_range.append(start + i*step)
    if retstep:
        return (np.array(list_range), step)
    else:
        return np.array(list_range)

# с использованием list comprehension
def my_linspace_lc(start, stop, num=50, endpoint=True, retstep=False):
    if endpoint:
        step = float(stop - start) / (num-1)
    else:
        step = float(stop - start) / num
    list_range = [ start + i*step for i in range(num) ]
    if retstep:
        return (np.array(list_range), step)
    else:
        return np.array(list_range)

In [3]:
np.linspace(1, 7, endpoint=True, retstep=True)

(array([ 1.        ,  1.12244898,  1.24489796,  1.36734694,  1.48979592,
         1.6122449 ,  1.73469388,  1.85714286,  1.97959184,  2.10204082,
         2.2244898 ,  2.34693878,  2.46938776,  2.59183673,  2.71428571,
         2.83673469,  2.95918367,  3.08163265,  3.20408163,  3.32653061,
         3.44897959,  3.57142857,  3.69387755,  3.81632653,  3.93877551,
         4.06122449,  4.18367347,  4.30612245,  4.42857143,  4.55102041,
         4.67346939,  4.79591837,  4.91836735,  5.04081633,  5.16326531,
         5.28571429,  5.40816327,  5.53061224,  5.65306122,  5.7755102 ,
         5.89795918,  6.02040816,  6.14285714,  6.26530612,  6.3877551 ,
         6.51020408,  6.63265306,  6.75510204,  6.87755102,  7.        ]),
 0.12244897959183673)

In [4]:
my_linspace_circle(1, 7, endpoint=True, retstep=True)

(array([ 1.        ,  1.12244898,  1.24489796,  1.36734694,  1.48979592,
         1.6122449 ,  1.73469388,  1.85714286,  1.97959184,  2.10204082,
         2.2244898 ,  2.34693878,  2.46938776,  2.59183673,  2.71428571,
         2.83673469,  2.95918367,  3.08163265,  3.20408163,  3.32653061,
         3.44897959,  3.57142857,  3.69387755,  3.81632653,  3.93877551,
         4.06122449,  4.18367347,  4.30612245,  4.42857143,  4.55102041,
         4.67346939,  4.79591837,  4.91836735,  5.04081633,  5.16326531,
         5.28571429,  5.40816327,  5.53061224,  5.65306122,  5.7755102 ,
         5.89795918,  6.02040816,  6.14285714,  6.26530612,  6.3877551 ,
         6.51020408,  6.63265306,  6.75510204,  6.87755102,  7.        ]),
 0.12244897959183673)

In [5]:
my_linspace_lc(1, 7, endpoint=True, retstep=True)

(array([ 1.        ,  1.12244898,  1.24489796,  1.36734694,  1.48979592,
         1.6122449 ,  1.73469388,  1.85714286,  1.97959184,  2.10204082,
         2.2244898 ,  2.34693878,  2.46938776,  2.59183673,  2.71428571,
         2.83673469,  2.95918367,  3.08163265,  3.20408163,  3.32653061,
         3.44897959,  3.57142857,  3.69387755,  3.81632653,  3.93877551,
         4.06122449,  4.18367347,  4.30612245,  4.42857143,  4.55102041,
         4.67346939,  4.79591837,  4.91836735,  5.04081633,  5.16326531,
         5.28571429,  5.40816327,  5.53061224,  5.65306122,  5.7755102 ,
         5.89795918,  6.02040816,  6.14285714,  6.26530612,  6.3877551 ,
         6.51020408,  6.63265306,  6.75510204,  6.87755102,  7.        ]),
 0.12244897959183673)

In [6]:
type(np.linspace(0, 7, endpoint=True)) == type(my_linspace_circle(0, 7, endpoint=True))

True

In [7]:
type(np.linspace(0, 7, endpoint=False)) == type(my_linspace_lc(0, 7, endpoint=False))

True

Сравним скорость выполнения:

In [9]:
%timeit np.linspace(0,11, 1000)
%timeit my_linspace_circle(0,11, 1000)
%timeit my_linspace_lc(0,11, 1000)

100000 loops, best of 3: 29 µs per loop
1000 loops, best of 3: 309 µs per loop
1000 loops, best of 3: 221 µs per loop


<b>Решение задачи 2:</b> Для сравнения производительности в качестве операций с массивами были выбраны суммирование элементов массива, поиск минимума и поиск максимума.

In [20]:
# генерируем одинаковые случайные последовательности с типами 'numpy.ndarray' и 'list'
test_np_array = np.random.randn(1000000)
test_list_array = list(test_np_array)

In [21]:
# сравнение суммирования элементов
%timeit test_np_array.sum()
%timeit sum(test_list_array)

100 loops, best of 3: 869 µs per loop
1 loop, best of 3: 274 ms per loop


In [26]:
# поиск минимума и максимума
%timeit test_np_array.min()
%timeit min(test_list_array)

%timeit test_np_array.max()
%timeit max(test_list_array)

1000 loops, best of 3: 716 µs per loop
10 loops, best of 3: 58.4 ms per loop
1000 loops, best of 3: 682 µs per loop
10 loops, best of 3: 37.3 ms per loop


<b>Решение задачи 3:</b>

In [27]:
from scipy import optimize


def f(x):
    return (x[0] - 3.2) ** 2 + (x[1] - 0.1) ** 2 + 3

print f([3.2, 0.1])

3.0


Ниже представлены методы, которые справились с задачей за 2 итерации. Точность у 'CG' и 'Powell' выше.

In [31]:
x_min = optimize.minimize(f, [5, 5], method='CG')
print x_min

     fun: 3.0
     jac: array([  0.00000000e+00,   2.98023224e-08])
 message: 'Optimization terminated successfully.'
    nfev: 20
     nit: 2
    njev: 5
  status: 0
 success: True
       x: array([ 3.19999999,  0.10000001])


In [30]:
x_min = optimize.minimize(f, [5, 5], method='Powell')
print x_min

   direc: array([[ 1.,  0.],
       [ 0.,  1.]])
     fun: 3.0
 message: 'Optimization terminated successfully.'
    nfev: 92
     nit: 2
  status: 0
 success: True
       x: array([ 3.19999999,  0.10000001])


In [37]:
x_min = optimize.minimize(f, [5, 5], method='SLSQP')
print x_min

     fun: 3.0000000000000058
     jac: array([ -1.19209290e-07,   5.96046448e-08,   0.00000000e+00])
 message: 'Optimization terminated successfully.'
    nfev: 9
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([ 3.19999993,  0.10000003])


In [34]:
x_min = optimize.minimize(f, [5, 5], method='L-BFGS-B')
print x_min

      fun: 3.0000000000006546
 hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>
      jac: array([  4.88498131e-07,  -1.55431223e-06])
  message: 'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
     nfev: 9
      nit: 2
   status: 0
  success: True
        x: array([ 3.20000025,  0.09999923])


## 2. Продвинутый уровень: изучаем изменения в документации sklearn

Установите себе самую свежую версию sklearn. В ней метод train_test_split должен быть в модуле model_selection, а не в cross_validation, как в старых версиях и в блокноте с лекции. Перепишите код с лекции так, чтобы вместо модуля sklearn.cross_validation он использовал sklearn.model_selection, и по-прежнему работал (продемонстрируйте это). Будьте внимательны к документации - сигнатура некоторых функций изменилась.

## 3. Сложный уровень: творческая часть

1. Заполните, пожалуйста, форму обратной связи по курсу: https://docs.google.com/forms/d/1aBPfORE8T3upInordGxPXZQiOPk4gFsIzvlimWerh7w Любые Ваши предложения могут быть очень ценны для нас, не стесняйтесь написать все, что думаете :)
1. Выберите любой модуль из не рассмотренных на последней лекции (можно взять любой из рекомендованных, можно любой на ваше усмотрение), напишите, зачем его используют и покажите несколько простых примеров его применения, предварительно разобравшись с ними в документации.

1. Заполнил.
2. Выбрал модуль json.

Модуль json позволяет кодировать и декодировать данные в формате json. json расшифровывается как JavaScript Object Notation. Это простой формат обмена данными, основанный на подмножестве синтаксиса JavaScript. В качестве примера работы с ним взял за основу задачу из базовой части 2-го ДЗ.

In [40]:
reviews = ["""Телефон абонента: +7 916 000 00 01
Время: 10:34
Дата: 20.05.2017
Оценка: 1
Длительность разговора (мин.): 0:32
Комментарий: Общение с сотрудником вашей техподдержки мне не понравилось. Раньше всегда отвечала девушка с приятным голосом, а сегодня какой-то мужчина. Совсем никуда не годится, примите меры!!!""",
"""Телефон абонента: +7 916 000 00 02
Время: 9:20
Дата: 21.05.2017
Оценка: 5
Длительность разговора (мин.): 25:07
Комментарий: С моей проблемой мне помогли, большое спасибо!"""]

In [41]:
my_base = {}
for info in reviews:
    strings = info.split('\n')
    my_base[strings[0].split(': ')[1]] = {param.split(': ')[0]: param.split(': ')[1] for param in strings[1:]}

In [44]:
import json

# пример записи словаря в json-файл
with open('test_json_file.json', 'w') as test_dump_file:
    json.dump(my_base, test_dump_file)

# пример чтения из json-файла
with open('test_json_file.json', 'r') as test_dump_file:
    dict_from_json = json.load(test_dump_file)

In [53]:
# Содержание файла
!type test_json_file.json

{"+7 916 000 00 02": {"\u041e\u0446\u0435\u043d\u043a\u0430": "5", "\u0412\u0440\u0435\u043c\u044f": "9:20", "\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439": "\u0421 \u043c\u043e\u0435\u0439 \u043f\u0440\u043e\u0431\u043b\u0435\u043c\u043e\u0439 \u043c\u043d\u0435 \u043f\u043e\u043c\u043e\u0433\u043b\u0438, \u0431\u043e\u043b\u044c\u0448\u043e\u0435 \u0441\u043f\u0430\u0441\u0438\u0431\u043e!", "\u0414\u0430\u0442\u0430": "21.05.2017", "\u0414\u043b\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u0440\u0430\u0437\u0433\u043e\u0432\u043e\u0440\u0430 (\u043c\u0438\u043d.)": "25:07"}, "+7 916 000 00 01": {"\u041e\u0446\u0435\u043d\u043a\u0430": "1", "\u0412\u0440\u0435\u043c\u044f": "10:34", "\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439": "\u041e\u0431\u0449\u0435\u043d\u0438\u0435 \u0441 \u0441\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a\u043e\u043c \u0432\u0430\u0448\u0435\u0439 \u0442\u0435\u0445\u043f\u043e\u0434\u0434\u0435